// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFn-K1nC2QrCjyR6ykgo9U6pexDd5OmiU',
    appId: '1:226173351869:web:bff81f586788671db144d4',
    messagingSenderId: '226173351869',
    projectId: 'smartdine-eb271',
    authDomain: 'smartdine-eb271.firebaseapp.com',
    storageBucket: 'smartdine-eb271.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfnOHEKDDXfsSP0tHAcmayLdV6xqq17wU',
    appId: '1:226173351869:android:8c79d918b71da552b144d4',
    messagingSenderId: '226173351869',
    projectId: 'smartdine-eb271',
    storageBucket: 'smartdine-eb271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWsRNPLuF1DS1Pip68MjuKdcJzxMDgI9w',
    appId: '1:226173351869:ios:2702e50fedd5cd83b144d4',
    messagingSenderId: '226173351869',
    projectId: 'smartdine-eb271',
    storageBucket: 'smartdine-eb271.firebasestorage.app',
    iosBundleId: 'com.example.meTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWsRNPLuF1DS1Pip68MjuKdcJzxMDgI9w',
    appId: '1:226173351869:ios:2702e50fedd5cd83b144d4',
    messagingSenderId: '226173351869',
    projectId: 'smartdine-eb271',
    storageBucket: 'smartdine-eb271.firebasestorage.app',
    iosBundleId: 'com.example.meTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFn-K1nC2QrCjyR6ykgo9U6pexDd5OmiU',
    appId: '1:226173351869:web:19bb778c0942209cb144d4',
    messagingSenderId: '226173351869',
    projectId: 'smartdine-eb271',
    authDomain: 'smartdine-eb271.firebaseapp.com',
    storageBucket: 'smartdine-eb271.firebasestorage.app',
  );

}